import { chromium } from "playwright";
const out = new URL("../../../artifacts/qa/", import.meta.url).pathname;
const b = await chromium.launch({ executablePath: process.env.PW_EXEC || undefined });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
p.on("pageerror", (e) => errs.push(String(e)));
const ok = (c, m) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) process.exitCode = 1; };
const count = async (s) => (await p.getByTestId(`count-${s}`).innerText()).trim();
const rows = () => p.locator("tbody tr").count();
await p.goto("http://localhost:3000"); await p.waitForTimeout(800);
await p.screenshot({ path: out + "01-dashboard.png" });
ok(await rows() === 6, "6 rows");
ok((await count("ready")) + (await count("review")) + (await count("blocked")) === "321", "counts 3/2/1");
await p.getByLabel("Search entities").fill("japan");
ok(await rows() === 1 && (await p.locator("tbody").innerText()).includes("Japan"), "search japan -> 1 row");
await p.getByLabel("Search entities").fill("zzz");
ok((await p.locator("tbody").innerText()).includes("No entities match"), "empty state");
await p.getByRole("button", { name: "Clear filters" }).click();
await p.getByLabel("Filter by status").selectOption("review");
ok(await rows() === 2, "filter review -> 2");
await p.getByLabel("Filter by status").selectOption("blocked");
ok(await rows() === 1, "filter blocked -> 1");
await p.getByLabel("Filter by status").selectOption("all");
await p.getByRole("button", { name: "Review Northwind Labs Inc." }).click();
const panel = p.getByRole("dialog");
const t = await panel.innerText();
ok(t.includes("USD 100,000.00") && t.includes("USD 135,000.00") && t.includes("35%") && t.includes("USD 35,000.00"), "panel totals + 35%");
ok(/sample analysis/i.test(t), "sample analysis label");
await p.screenshot({ path: out + "02-panel.png" });
await panel.getByRole("button", { name: "Mark as reviewed" }).click();
await p.waitForTimeout(200);
ok((await p.getByRole("status").innerText()).includes("marked as reviewed"), "confirmation toast");
ok(await count("ready") === "4" && await count("review") === "1", "counts 4/1/1 after review");
await p.screenshot({ path: out + "03-reviewed.png" });
await p.reload(); await p.waitForTimeout(800);
ok(await count("ready") === "4", "persists after refresh");
await p.getByRole("button", { name: "Review Northwind Labs Inc." }).click();
ok((await p.getByRole("dialog").innerText()).includes("Variance reviewed on"), "panel shows reviewed state after refresh");
await p.keyboard.press("Escape");
ok(await p.getByRole("dialog").count() === 0, "Escape closes panel");
await p.getByRole("button", { name: "Reset demo" }).click(); await p.waitForTimeout(200);
ok(await count("ready") === "3" && await count("review") === "2", "reset restores 3/2/1");
await p.reload(); await p.waitForTimeout(800);
ok(await count("ready") === "3", "reset persists after refresh");
await p.setViewportSize({ width: 390, height: 844 });
await p.screenshot({ path: out + "04-mobile.png" });
ok(errs.length === 0, "no browser errors " + JSON.stringify(errs));
await b.close();
